# Generated by Django 3.0.5 on 2020-04-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_story', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('recipe', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
