# Generated by Django 3.0.5 on 2020-06-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200618_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='recipe',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
