# Generated by Django 3.0.5 on 2020-08-15 07:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200618_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='back_story',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='content'),
            preserve_default=False,
        ),
    ]
