# Generated by Django 3.0.5 on 2020-08-19 19:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='recipe',
        ),
        migrations.AddField(
            model_name='post',
            name='extra_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='instructions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='serving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
