# Generated by Django 3.0.5 on 2020-05-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=3000)),
                ('extra_info', models.CharField(blank=True, max_length=3000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=3000)),
                ('extra_info', models.CharField(blank=True, max_length=3000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=3000)),
                ('extra_info', models.CharField(blank=True, max_length=3000, null=True)),
                ('price', models.IntegerField()),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_cat', to='menu.Category')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='menu.SubCategory')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
